### ISSUE TITLE
NoBackendError problem

### ISSUE THREAD

**Issue by skovacevic96** [beetbox/audioread#107]
Hello, I have a problem. Already described it here: https://stackoverflow.com/questions/61160696/python-librosa-nobackenderror-even-though-ffmpeg-is-installed
I am posting it in this thread as I've found out is related to audioread. I've already went through this entire thread and saw some other people talking about the same problem. Some said that they did manage to do something about it but none of that worked for me. Why is this happening and is there any way to fix it? Thanks!

**Comment by macabdul9** [comment]
@slavzilla Were you able to resolve the issue?
