### ISSUE TITLE
Use gobject-introspection (gi) instead of pygst

### ISSUE THREAD

**Issue by sampsyo** [beetbox/audioread#11]
We should move the GStreamer backend to python-gobject-instrospection. This is the latest recommendation and is Py3k-compatible, unlike the pygst library.

**Comment by jrobeson** [comment]
I've made some progress on this. Do we still want to support gstreamer 0.10 at all? I don't think we should bother, but it's up to you.

**Comment by sampsyo** [comment]
Awesome! :sparkles:

No, I agree we should drop it altogether.

**Comment by sampsyo** [comment]
I just noticed this is still open—we've moved on some time ago now with 2.0.0.
