### ISSUE TITLE
pytest-runner not required

### ISSUE THREAD

**Issue by pgajdos** [beetbox/audioread#118]
Deprecated pytest-runner is not necessary to run the testsuite.

**Comment by sampsyo** [comment]
Hello! I'm not quite sure what you mean. We no longer use pytest-runner:
https://github.com/beetbox/audioread/commit/8879cc802c730349a1213a415155ea3014431f69

Can you please explain a little more about what you would like to see changed?

**Comment by pgajdos** [comment]
Yep, I have not noticed the recent changes. Thanks!
