### ISSUE TITLE
Missing v3.0.1 release

### ISSUE THREAD

**Issue by mfansler** [beetbox/audioread#136]
There seem to be some notes on a v3.0.1 release, but no formal Release created or build pushed to PyPI. Could this be done?

Currently, the v3.0.0 release is incompatible with Python 3.12 due to use of the `imp` library (now removed). This has been addressed here, so it would be nice to have a usable version out in circulation.

**Comment by sampsyo** [comment]
Sure thing! I have tagged and published v3.0.1. Here's the compare view:
https://github.com/beetbox/audioread/compare/v3.0.0...main

I don't see any direct uses of `imp` being removed... but hopefully this solves the problem anyway.
