### ISSUE TITLE
Getting segmentation fault after using audioread for MP4s

### ISSUE THREAD

**Issue by devangel77b** [beetbox/audioread#14]
I had been using audioread to get the audio from MP4 videos from different cameras, in order to synchronize them.  

I have noticed that I am now getting a segmentation fault when all is done, and have debugged it to be something in audioread.  Some minimal code to get this is included below. The expected behavior is it should open the MP4 file, do its thing, and exit; what I get is it does its thing but exits with a segmentation fault. I have commented out all remaining imports (cv2 and numpy) and I still get the segmentation fault.   Platform is up-to-date Linux Ubuntu 14.04; the problem does not occur on a Mac.  audioread is using gstdec to go through the MP4 and I tried both the 

with audioread.audio_open() as f 

and the current 

try: (etc) finally: f.close() 

syntax listed in the audioread docs.  Perhaps there is a problem in how the stream is closed, or in gstreamer? 

Any suggestions?
-Dennis

#!/usr/bin/env python

#import cv2
import audioread
#import numpy as np

if __name__ == "__main__":

    # THIS PART IS OK
    #blue = cv2.VideoCapture("blue.MP4")
    #print ("Blue fps: {0}".format(blue.get(cv2.cv.CV_CAP_PROP_FPS)))
    #blue = None

    # THIS PART RUNS OK BUT.... 
    temp = bytearray()
    f = audioread.audio_open("blue.MP4")
    try:
        samplerate = f.samplerate
        duration = f.duration
        channels = f.channels
        for block in f:
            #print np.frombuffer(block,dtype=np.int16)
            temp.extend(block)
    finally:
        f.close()
        f = None

    #signal = np.frombuffer(temp,dtype=np.dtype('<i2')) #.reshape(-1,channels)
    print f
    print samplerate,duration,channels
    #print signal

    # IT GIVES SEG FAULT HERE AT END OF RUNNING, UPON EXITING

**Comment by jrobeson** [comment]
I wonder if this is still valid now. Is it?

**Comment by sampsyo** [comment]
Good catch; no. Should be cleared up (or at least different) now that we're on 1.x.
