### ISSUE TITLE
Deprecation warnings in gstdec.py

### ISSUE THREAD

**Issue by Nerten** [beetbox/audioread#24]
```
/usr/local/lib/python2.7/dist-packages/audioread/gstdec.py:126: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/usr/local/lib/python2.7/dist-packages/audioread/gstdec.py:146: PyGIDeprecationWarning: MainLoop is deprecated; use GLib.MainLoop instead
  self.loop = GObject.MainLoop()
```

**Comment by sampsyo** [comment]
Thanks. To fix this, we'll need to do some investigation on both of these:

* Are there older versions out there that will break, or can we safely remove the `threads_init` call?
* How early was `GLib.MainLoop()` available?

In both cases, we may need to check the version to choose what to do.

**Comment by simonbcn** [comment]
same problem:

/usr/local/lib/python2.7/dist-packages/audioread/gstdec.py:126: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/usr/local/lib/python2.7/dist-packages/audioread/gstdec.py:146: PyGIDeprecationWarning: MainLoop is deprecated; use GLib.MainLoop instead
  self.loop = GObject.MainLoop()

**Comment by smcv** [comment]
> Are there older versions out there that will break, or can we safely remove the threads_init call?

`g_threads_init()` was necessary before GLib 2.32 (2012). How far back do you intend to support?

> How early was GLib.MainLoop() available?

Even if you're only counting stable versions, this has been available since pygobject 2.16 (2008):

```
2.15.2 26-jul-2008
        - New module: glib, which contains the parts of the old
          gobject bindings which are in the glib library.
          MainLoop/MainContext/Sources/GOption and a few others has now moved.
```

**Comment by smcv** [comment]
> this has been available since pygobject 2.16

In particular, if you have the `gi.repository` module, it is always correct to import `MainLoop` from `gi.repository.GLib`, and never from `gi.repository.GObject`.

I'd recommend dropping support for the old static bindings (GStreamer 0.10, `import GLib`, `import GObject`) and only supporting `gi.repository` and GStreamer 1.0.

**Comment by sampsyo** [comment]
Thanks for the advice, @smcv! Assuming a 2012 version of Glib seems 100% reasonable to me. Does #30 look right to you (or should we use some sort of standard version check)?

**Comment by smcv** [comment]
I'd merge #30 if it was my project. I don't think it's really worthwhile adding a version check, but if you wanted one, it would be:

```
if GLib.check_version(2, 32, 0) is None:
    ... # GLib is new
else:
    ... # GLib is old, the result of check_version() is a string explaining how
```

**Comment by sampsyo** [comment]
That's good enough for me. Thanks again for your advice!
