### ISSUE TITLE
bus unref needed in GstAudioFile

### ISSUE THREAD

**Issue by khlukekim** [beetbox/audioread#28]
Hi, I got an error while calling audio_open() several times(with .mp3 files). Looks like it is due to accumulated refs of bus objects in GstAudioFile. I gave it a monkey patch and apparently it seems fine. However, since my files are not gst-encoded, I'm not sure whether this would cause any problem with actual gst decoding tasks.

In my case, I inserted following lines in GstAudioFile.close():
```
bus = self.pipeline.get_bus()
bus.unref()
bus.remove_signal_watch()
```

**Comment by sampsyo** [comment]
Good catch; thanks! Would you mind opening a PR with those changes? I'll run them through a battery of tests.
