### ISSUE TITLE
ffmpeg backend mucks with standard input on `close()`

### ISSUE THREAD

**Issue by sampsyo** [beetbox/audioread#32]
As discovered in https://github.com/beetbox/beets/issues/2039, we appear to cause problems on `f.close()` in with the FFmpeg backend. Specifically, subsequent calls to read from standard input (i.e., `raw_input()` calls) no longer receive any keyboard input.

This is easy to reproduce with this tiny test script:

```py
import audioread.ffdec
f = audioread.ffdec.FFmpegAudioFile('xxx.m4a')
f.close()
raw_input('prompt: ')
```

I was able to narrow down the problem to e31af0b5febba7aa07bd24c0065ba5faf93eacc0, which was our fix for #9. If I change that line to send SIGTERM instead of SIGKILL to the ffmpeg process, everything works fine.

**Comment by sampsyo** [comment]
That seems to fix it on my machine. It's still a bit of a mystery as to why this didn't appear before—it may have arisen only in recent (3.0?) versions of FFmpeg.

**Comment by mtompkins** [comment]
If this fix  was incorporated in [beets v1.3.19](https://github.com/beetbox/beets/releases/tag/v1.3.19) just sharing here that the condition still exists.

**Comment by sampsyo** [comment]
Hi! Have you upgraded audioread?

**Comment by mtompkins** [comment]
I executed a `pip install beets --upgrade` presuming it would handle any necessary dependencies. Is this something that needs to be done explicitly?

Appreciate the hand-holding. . .

**Comment by sampsyo** [comment]
You'll needs upgrade audioread explicitly because it's not a beets dependency—it's only used for the chroma plugin.

**Comment by mtompkins** [comment]
Ah makes sense, thanks so much. 
Can also confirm this resolved it.

Many thanks!

**Comment by sampsyo** [comment]
Woohoo!
