### ISSUE TITLE
Conda-forge packaging

### ISSUE THREAD

**Issue by bmcfee** [beetbox/audioread#33]
Hey, at the scipy2016 sprints, I took the liberty of making a conda forge recipe and feedstock for audioread. This way, downstream libraries can be packaged on conda easily.

I don't mind maintaining this for a bit, but ownership/write access should probably move to this org at some point. What's the best way to manage this?

**Comment by bmcfee** [comment]
For reference, the repo lives here: https://github.com/conda-forge/audioread-feedstock

**Comment by sampsyo** [comment]
Great! Thanks! I don't know anything about Conda, but it seems fine to move it to the @beetbox org. Feel free to transfer it whenever you think it's ready.

**Comment by bmcfee** [comment]
@sampsyo The thing about feedstocks is that they live under the conda-forge org, so you can't really own/transfer them.  (I don't own the recipe either.)  I'll add you to the maintainers list though.  It's probably worth browsing the readme in that repo to see the process for updating the packages after a new release.

**Comment by sampsyo** [comment]
Got it; that works. I can't guarantee I'll always remember to update the package, but now we at least have more than one person who has a shot at remembering.
