### ISSUE TITLE
DecodeErrors leak file descriptors

### ISSUE THREAD

**Issue by bmcfee** [beetbox/audioread#41]
I noticed this warning popping up in librosa's unit tests:

```
/home/travis/env/miniconda3.4/envs/test-environment/lib/python3.4/site-packages/audioread/__init__.py:80: ResourceWarning: unclosed file <_io.BufferedReader name='/home/travis/build/librosa/librosa/librosa/util/example_data/Kevin_MacLeod_-_Vibe_Ace.ogg'>
```

After digging into it, I think the problem is that the `RawAudioFile` object first opens the target file [here](https://github.com/beetbox/audioread/blob/master/audioread/rawread.py#L49) and then later throws an exception if the file cannot be decoded [here](https://github.com/beetbox/audioread/blob/master/audioread/rawread.py#L80).  The initial file descriptor (`self._fh`) is never explicitly closed; the warning pops up on python 3 when the object goes out of scope and gets garbage collected.

While this isn't a major problem since the descriptors are read-only and things do eventually get hit by the GC, it should be easily avoidable by closing the handle before raising the `UnsupportedError` exception.

**Comment by sampsyo** [comment]
Thanks for pointing this out! For posterity, it was pretty easy to reproduce the warning with the included `decode.py` if you use the `-Wdefault` flag:

```
$ python3 -Wdefault decode.py full.mp3
/Users/asampson/code/audioread/audioread/__init__.py:80: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/asampson/code/audioread/full.mp3'>
  pass
Input file: 1 channels at 44100 Hz; 1.0 seconds.
Backend: macca
```

I'll fix this now.

**Comment by bmcfee** [comment]
Thanks for the quick fix!

Does this issue affect other decoders as well?  [Mad](https://github.com/beetbox/audioread/blob/master/audioread/maddec.py#L25-L28) looks like it does, the others are a bit harder for me to spot-check.

**Comment by sampsyo** [comment]
Thanks for pointing that out too! I fixed that one too.

The other backends don't use `open` to get at the audio file's data, so I think they're safe from this exact problem.
