### ISSUE TITLE
audioread.__version__

### ISSUE THREAD

**Issue by bmcfee** [beetbox/audioread#49]
It would be great if audioread exposed its current version information in the standard place (`audioread.__version__`).

This would be useful mainly for upstream debugging / error reporting.

**Comment by sampsyo** [comment]
Good call; yes! The only cost, of course, is that I'll need to remember to update the version in one more location. :smiley: Or maybe we should use the trick described [here, in PEP 396](https://www.python.org/dev/peps/pep-0396/#classic-distutils)?

In any case, would you mind opening a tiny PR to add the variable?

**Comment by bmcfee** [comment]
Sure, I'll take a crack at this either tonight or tomorrow.

FWIW, I do something similar to that trick in librosa (and most of my other projects):

- https://github.com/librosa/librosa/blob/master/setup.py#L5

and

- https://github.com/librosa/librosa/blob/master/librosa/__init__.py#L7
- https://github.com/librosa/librosa/blob/master/librosa/version.py

This way it only needs to get updated in one place.  Not counting git tags, of course.
