### ISSUE TITLE
Gstreamer/PyGObject breaks SIGINT handling

### ISSUE THREAD

**Issue by albertz** [beetbox/audioread#63]
`GLib.MainLoop.__init__ ` installs a SIGINT handler which calls `GLib.MainLoop.quit()`,
and then reraise a KeyboardInterrupt in that thread.
However, the main thread will not notice that, and continues whatever it is doing, which mostly means that it will hang as it is waiting for something.
What you would want is a KeyboardInterrupt in the main thread, as this is the original behavior when you press Ctrl+C.

I came up with this workaround / ugly monkey patch to just disable the SIGINT handler.
However, a better fix would be in PyGObject to raise the KeyboardInterrupt in the main thread.

```
def monkeyfix_glib():
  """
  Fixes some stupid bugs such that SIGINT is not working.
  This is used by audioread, and indirectly by librosa for loading audio.
  https://stackoverflow.com/questions/16410852/
  """
  try:
    import gi
  except ImportError:
    return
  try:
    from gi.repository import GLib
  except ImportError:
    from gi.overrides import GLib
  # Do nothing.
  # The original behavior would install a SIGINT handler which calls GLib.MainLoop.quit(),
  # and then reraise a KeyboardInterrupt in that thread.
  # However, we want and expect to get the KeyboardInterrupt in the main thread.
  GLib.MainLoop.__init__ = lambda *args, **kwargs: None
```

**Comment by sampsyo** [comment]
Hmm; I don't think I quite understand. What do you mean by "the original behavior" here? Are you saying that GLib itself (or perhaps GStreamer, or perhaps PyGObject—not sure which) installs a SIGINT handler when it's loaded? If the latter, perhaps this bug is best addressed in one of those projects instead of audioread itself?

**Comment by albertz** [comment]
Sorry, bad formulation. I edited it. Yes, Glib installs a SIGINT handler, and the main Python thread will never get a KeyboardInterrupt, which is not what you want.

**Comment by sampsyo** [comment]
Ah, I see! So perhaps the right thing to do would be to add a `KeyboardInterrupt` handler around the `self.loop.run()` call in `MainLoopThread` and explicitly signal the main thread to stop? That would be a little hairy…

Perhaps this SO answer points to a reasonable alternative?
https://stackoverflow.com/a/16486080/39182

**Comment by albertz** [comment]
Yes, that would be another solution. You can use `thread.interrupt_main()` to do that.

The SO solution is not so nice as it would just kill your Python program (I think) and not do the proper handling which you might want for KeyboardInterrupt. Actually, calling audioread should just not change the behavior of that in any way.

**Comment by lazka** [comment]
fyi, pygobject 3.28+ will no longer install a signal handler there if one was already set before and will no longer change anything when not run in the main thread.

There is an easier fix to work around all this:

instead of `GLib.MainLoop()` do `GLib.MainLoop.new(None, False)` in audioread

**Comment by sampsyo** [comment]
Awesome, @lazka; thank you for the background.

Do you happen to know where in the docs I can learn about the difference between the `MainLoop()` constructor and the `MainLoop.new(None, False)` call? [These docs](https://lazka.github.io/pgi-docs/GLib-2.0/structs/MainLoop.html#GLib.MainLoop.new), for example, mention the `new` classmethod, which clearly corresponds to the underlying [g_main_loop_new](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-main-loop-new) function, but it's not clear what using the constructor was doing.

**Comment by lazka** [comment]
> Do you happen to know where in the docs I can learn about the difference between the MainLoop() constructor and the MainLoop.new(None, False) call? These docs, for example, mention the new classmethod, which clearly corresponds to the underlying g_main_loop_new function, but it's not clear what using the constructor was doing.

Sadly nowhere. `__init__` was the (buggy) code @albertz posted above before, now it does nothing and the improved logic is in run() instead. new() returns an already initialized instance (from C) and skips __init__.

**Comment by sampsyo** [comment]
Got it; thanks again for the background about how this happened!
