### ISSUE TITLE
Reading from from Buffer

### ISSUE THREAD

**Issue by loretoparisi** [beetbox/audioread#92]
I'm using gensim `smart_open` to read the audio file directly from AWS S3:

```
with open('s3://mybucket/myprefix/audio.mp3', 'rb') as fin:
    y, sr = librosa.load(fin.read(), offset=30, duration=5)
    print(sr)
```

The problem is that `librosa.read` that uses `audioread.audio_open` seems to not support reading from a buffer, but only a path.
Is there any other way? Not sure if this can be related to https://github.com/beetbox/audioread/issues/35
Thank you

**Comment by sampsyo** [comment]
Please see #53.

**Comment by loretoparisi** [comment]
@sampsyo thank you. Any plan to merge the `audio.decode` to the master branch?

**Comment by sampsyo** [comment]
Looks like that branch needs a little help to deal with a Python 2 issue, do some testing, and write some documentation! Any chance you'd be interested in helping out?
